accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name='work.html'), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

app/urls.py
from django.urls import path
from .views import ContactViews, AboutViews, WorkViews,ProfileView,ResumeViews

app_name = 'app'

urlpatterns = [
    path('', ResumeViews.as_view(), name='contacts'),
    path('about/', AboutViews.as_view(), name='about'),
    path('work/', WorkViews.as_view(), name='work'),
    path('contact/', ContactViews.as_view(), name='contact'),
    path("accounts/profile/", ProfileView.as_view(), name="profile"),

]

portofolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('accounts', include('accounts.urls', namespace='accounts'))

]

accounts/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone


class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)

app/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=10)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.subject

    

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from . import forms

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/signup.html"

app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from .models import Contact
# Create your views here.

class ContactViews(CreateView):
    model = Contact
    fields = ('__all__')
    template_name = 'contact.html'

class ResumeViews(TemplateView):
    template_name = 'resume.html'

class AboutViews(TemplateView):
    template_name = 'about.html'

class WorkViews(TemplateView):
    template_name = 'work.html'

class ProfileView(TemplateView):
    template_name = "profile.html"

accounts/templates/accounts/login.html
{% extends "base.html" %}
<!-- load bootstrap3  -->

{% block content %}
<div class="container jumbotron card p-5 login-form">
    <h1 >Login</h1>
    <form class="container" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button  class="btn btn-info pull-right btn-lg" href="{% url 'app:work' %}">Login</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}



{% block content %}
<div class=" container login-form jumbotron p-4">
    <h1>Please create a login here.</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign Up" class="btn btn-success">
    </form>
</div>
{% endblock %}

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1 class="h2">01 : About me</h1>
        <div class="img-cent cent mybg2">
            <img src="{% static 'img/me4.png' %}" class="img-responsive" height="300px" width="300px" alt="" >
        </div>

            <div class="text-center">

            </div>
            <p>Nulla facilisi. Vivamus vestibulum, elit in scelerisque ultricies, nisl nunc pulvinar ligula, id
                sodales arcu sapien in nisi. Quisque libero enim, mattis non augue posuere, venenatis dapibus
                urna.</p>

            <blockquote>
                <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante."</p>
                <small class="pull-right">Irina Martin</small>
            </blockquote>
        </div>
    </div>
</div>

<div class="section-container">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="section-container-spacer text-center">
                </div>
                <div class="container">
                        <div class="row">
                            <div class="col-xs-12 col-md-6">
                                <h3>Consectetur adipiscing elit</h3>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas luctus at sem quis
                                    varius.
                                    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos
                                    himenaeos. Cras ultrices hendrerit nisl.</p>
                                <h3>Ut enim ad minim </h3>
                                <p>Duis aute irure dolor in reprehenderit in voluptate velit esse
                                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                                <h3>Maecenas luctus at sem quis varius</h3>
                                <p>
                                    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos
                                    himenaeos. Phasellus iaculis magna sagittis elit sagittis, at hendrerit lorem
                                    venenatis. Morbi accumsan iaculis blandit. Cras ultrices hendrerit nisl.</p>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!-- <link rel="stylesheet" href="  static 'css/master.css'"> -->
    <!-- <link rel="stylesheet" href=" static 'css/style.css' "> -->
    <link rel="stylesheet" href="{% static 'css/my-style.css' %}">


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:300;400;600;700;800&display=swap" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <link href="/static/img/favicon.ico" rel="icon">

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:300;400;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>


<body>
    <nav class="navbar fixed-top navbar-expand-lg text-light navbar-dark bg-dark position-sticky ">
        <div class="container-fluid">
            
            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="/about">
                <strong class="text-primary">Zelalem Smith</strong>
            </a>
    
            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-pills btn waves-effect text-primary" href="/about">
                            About</a>
                    </li>
                    <li  class="nav-item">
                        <a href="/" class="nav-pills btn waves-effect text-primary">Resume</a>
                    </li>
                    <li class="nav-item">
                        <a href=" {% url 'app:work' %}" class="nav-pills btn waves-effect text-primary">Work</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-pills btn waves-effect text-primary" href="/contact">Contact Us
                        </a>
                    </li>
                </ul>
    
                <!-- Right -->
                <ul class="navbar-nav nav-flex-icons pull-right ">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'accounts:logout' %}">
                            <span  class=" text-info btn clearfix d-none d-sm-inline-block"> Logout </span>
                        </a>
                    </li>
                    
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'accounts:login' %}">
                            <span class=" text-info btn clearfix d-none d-sm-inline-block"> Login </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'accounts:signup' %}">
                            <span class=" text-info btn clearfix d-none d-sm-inline-block"> Signup </span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
    
        </div>
    </nav>


        {% block content %}

        {% endblock %}


    <script src="{% static '/js/master.js' %}" type="text/javascript"></script>
    <script src="{% static '/js/contact.js' %}" type="text/javascript"></script>
    <script src="{% static '/js/main.js' %}" type="text/javascript"></script>
    <script src="{% static  '/js/easing.js' %}" type="text/javascript"></script>
    <script src="{% static  '/js/easing.js' %}" type="text/javascript"></script>
    <script src="js/jqBootstrapValidation.min.js" type="text/javascript"></script>


    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
        crossorigin="anonymous"></script>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
</body>

</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% block content %}
  
<div class="container ">
        <h1 class="h2 ">Contact me</h1>

    <div class="cent mybg">

        <form class="" method="post">
                <div class=" col-sm-12 col-md-12 ">

                    <h3 class="m-5">
                    {% csrf_token %}

                    {{ form.as_p }}

                    </h3>
                    <a class="btn btn-primary text-light pull-right" href="/submit">Submit</a>
                </div>
        </form>
    </div>


{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loged in</title>
</head>
<body>
    {% block content %}
    <div class="container">

    <h1 class="text-center bold">
        Welcome, {{user.username}}
    </h1>    

    </div>


    {% endblock content %}

</body>
</html>

templates/resume.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container ">
    <div class="row card">
        <h1 class="mybg cent">
            Introduction:
        </h1>
        <h5 class="p-2">
            I am a self stater, a fast learner and I am a hard worker. I have backgrounds in customer service,
            management roles,
            warehouse, e-commerce, inventory control, software development. I enjoy learning new skills and leading
            by example. I am
            a self-taught programer in Python and currently a student for a bachelor's in computer science.
        </h5>
        <h4 class="">Contact:</h4>
        <h6 class=""><strong>Email:</strong> zele713@gmail.com</p>
            <h6 class=""><strong>Phone Number:</strong>(951)-532-1362 </h6>
    </div>
        <h1 class="mt-5 cent mybg">Experices:</h1>
        </div>
        <div class="container ">
        <div class="row">
            <div class=" col-sm-12 col-md-6 col-lg-6 card-header ">
                <h5 class="m1">
                    <p> <strong>Role: </strong>Ecommerce Product Manager</p>
                    <p class=""> <strong> <strong>Company: </strong>Y&A Group LLC - Gardena, CA</strong></p>
                    <p><strong>Date Range:</strong> April 2020 to August 2021</p>
                    <strong>Detail: </strong>
                    <p class="">
                        I was the only employee the owner had. (this was a warehouse job where we buy and sell on all
                        e-commerce platforms. My
                        duties were receive products, test products, clean and take pictures, pst products on ebay,
                        bonanza, Amazon, Walmart
                        and ship orders, handle and resolve customer problems. Using Django models with Python I created
                        an inventory system to
                        manage products.
                    </p>
                </h5>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6 card-header">
                <h5 class="m1">
                <p> <strong>Role: </strong>Ecommerce Product Manager</p>
                <p> <strong>Company: </strong> UPS - Lenexa, KS</p>
                <p><strong>Date Range: </strong> July 2018 to September 2019</p>
                <strong>Detail: </strong>

                <p class="">
                    I started as a loader, but I was promoted to a sort-isle supervisor. As the supervisor for the
                    sorting isle, I managed
                    12 to 15 employees per night. My duties were Inspecting equipments, demonstrate safe pfting and
                    lower methods, and
                    handpng hazards materials, manage each employee hours, employee payroll hours entry adjustments,
                    communicated through
                    radio to solve problems that occur. ill out paper work at the beginning of shift and at end of
                    shift for inspections on
                    equipment and employees.
                </p>
                </h5>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6 card-header">
                <h5 class="m1">
                <p> <strong>Role: </strong> Ecommerce Product Manager</p>
                <p> <strong>Company: </strong>Y&A Group LLC - Gardena, CA </p>
                <p><strong>Date Range: </strong>April 2020 to August 2021 </p>
                <strong>Detail: </strong>
                <p class="">
                    I was the only employee the owner had. (his was a warehouse job where we buy and sell on all
                    e-commerce platforms.
                    My
                    duties were receive products, test products, clean and take pictures, pst products on ebay,
                    bonanza, Amazon,
                    Walmart
                    and ship orders, handle and resolve customer problems. Using Django models with Python I created
                    an inventory system
                    to
                    manage products.
                </p>
                </h5>
            </div>
        </div>
    </div>
</div>
</div>
<div class="container">
<div class="row">
    <h1 class="cent mybg"> Skill:</h1>

    <div class=" col col-sm-12 col-md-6 col-lg-6 cent  mt-2 cent">
            <img height="400px" width="400px" src="{% static 'img/software-programming.png' %}" alt="certification">
    </div>
    <div class=" col col-sm-12 col-md-6 col-lg-6 cent  mt-2 cent">
        <img height="400px" width="400px" src="{% static 'img/software-architecture.png' %}" alt="certification">
    </div>
   
    <div class="card cent col-sm-12 col-md-6 col-lg-6">
        <h5><strong class="card-body">Software: Back-end languages</strong></h5>
        <a href="" class="btn">Python </a>
        <a href="" class="btn">Java </a>
        <a href="" class="btn">JavaScript & NodeJS </a>
    </div>

    <div class="cent card col-sm-12 col-md-6 col-lg-6">
        <h5><strong class="">Data Mangment:</strong></h5>
        <a href="" class="btn">Postgerse </a>
        <a href="" class="btn">MySQL </a>
        <a href="" class="btn">React </a>
    </div>
    <div class="cent card col-sm-12 col-md-6 col-lg-6">
        <h5><strong class="">UI: Front-end tools</strong></h5>
        <a href="" class="btn">CSS </a>
        <a href="" class="btn">Html </a>
        <a href="" class="btn">JavaScript & jQuery</a>
    </div>
    <div class="card cent col-sm-12 col-md-6 col-lg-6">
        <h5><strong>Frameworks & Tools </strong></h5>
        <a href="" class="btn">Django </a>
        <a href="" class="btn">Git </a>
        <a href="" class="btn">React </a>
        <a href="" class="btn">jQuery </a>
        <a href="" class="btn">Bootstrap </a>
        <a href="" class="btn">GitHub </a>
        <a href="" class="btn">Angular</a>
    </div>
    </div>
    </div>
    <hr>
    </div>
</div>
</div>
<div class="container dark-grey-text mt-5">

    <h1 class="md-3 cent mybg"> Education & Certifications: </h1>

        <!--Grid row-->
        <div class="row wow fadeIn cent">

            <!--Grid column-->
            <div class="col-md-6 mb-4 ml-2">
                <img height="300px" width="300px" src="{% static 'img/woz-u-certification.png' %}" alt="certification">
            </div>
            <!--Grid column-->
            <div class="col-md-6 mb-4 ml-2">
                <img height="300px" width="300px" src="{% static 'img/Python_Developer_Certification.png' %}" alt="certification">
            </div>
            <div class="col-md-6 mb-4 ml-2">
                <img height="300px" width="300px" src="{% static 'img/IMG_0127.JPG' %}" alt="certification">

            </div>
            <!--Grid column-->
            <div class="col-md-6 mb-4 p-4">

                <div class="jumbotron mt-2 cent " width="400px">
                    <p> <strong>Central Heights High Scool: <br></strong> </p>
                    August 2012 - May 2016:
                    High School Diploma
                    </p>
                </div>
                <div class="p-4">
            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

   
        </div>
    </div>
</div>



{% endblock %}

templates/work.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
<h1 class="text-center">My Designs:</h1>
<div class="section-container">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <img src="{% static 'img/web.png' %}" class="img-responsive" alt="">
                <div class="card-container">
                    <div class="text-center">
                        <h1 class="h2">001 : Fringilla sit amet</h1>
                    </div>
                    <p>Nulla facilisi. Vivamus vestibulum, elit in scelerisque ultricies, nisl nunc pulvinar ligula, id
                        sodales arcu sapien in nisi. Quisque libero enim, mattis non augue posuere, venenatis dapibus
                        urna.</p>

                    <blockquote>
                        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante."</p>
                        <small class="pull-right">Irina Martin</small>
                    </blockquote>
                </div>
            </div>



            <div class="col-md-8 col-md-offset-2 section-container-spacer">
                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <img src="{% static 'img/blog-1.jpg' %}" class="img-responsive" alt="">
                        <p>Menphis skyline</p>
                    </div>
                    <div class="col-xs-12 col-md-6">
                        <img src="{% static 'img/blog-2.jpg' %}" class="img-responsive" alt="">
                        <p>Menphis skyline</p>
                    </div>
                </div>
            </div>

            <div class="col-xs-12">
                <img src="{% static 'img/carousel-3.jpg' %}" class="img-responsive" alt="">
            </div>

        </div>
    </div>
</div>
</div>
{% endblock  %}